from reportlab.platypus import (
    SimpleDocTemplate,
    Paragraph,
    Spacer,
    Table,
    TableStyle
)
from reportlab.lib import colors
from reportlab.lib.styles import getSampleStyleSheet
import os


def generate_pdf(report_data, filename):

    os.makedirs("reports", exist_ok=True)

    pdf_path = os.path.join("reports", filename)

    doc = SimpleDocTemplate(pdf_path)

    styles = getSampleStyleSheet()

    elements = []

    # Title
    title = Paragraph(
        "<b><font size=20 color='blue'>🚀 PipelineGuard</font></b>",
        styles["Title"]
    )

    subtitle = Paragraph(
        "<b>Pipeline-as-Code Linter & Validator</b>",
        styles["Heading2"]
    )

    elements.append(title)
    elements.append(subtitle)
    elements.append(Spacer(1, 20))

    # Overall Result
    status = report_data.get("status", "Unknown")

    if status == "Passed":
        status_text = "<font color='green'><b>VALIDATION PASSED</b></font>"
    else:
        status_text = "<font color='red'><b>VALIDATION FAILED</b></font>"

    elements.append(Paragraph(status_text, styles["Heading2"]))
    elements.append(Spacer(1, 20))

    # Report Table
    table_data = [

        ["Field", "Value"],

        ["File Type", report_data.get("file_type", "-")],
        ["Status", report_data.get("status", "-")],
        ["Warnings", str(report_data.get("warnings", 0))],
        ["Errors", str(report_data.get("errors", 0))],
        ["Validation Result", report_data.get("message", "-")],

        ["Security Status",
         report_data.get("security_status", "-")],

        ["Security Severity",
         report_data.get("security_severity", "-")],

        ["Security Result",
         report_data.get("security_message", "-")],

        ["Timestamp",
         report_data.get("timestamp", "-")]

    ]

    table = Table(table_data, colWidths=[170, 300])

    table.setStyle(TableStyle([

        ("BACKGROUND", (0, 0), (-1, 0), colors.darkblue),
        ("TEXTCOLOR", (0, 0), (-1, 0), colors.white),

        ("GRID", (0, 0), (-1, -1), 1, colors.black),

        ("BACKGROUND", (0, 1), (0, -1), colors.lightgrey),

        ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
        ("FONTNAME", (0, 1), (0, -1), "Helvetica-Bold"),

        ("BOTTOMPADDING", (0, 0), (-1, 0), 12),

    ]))

    elements.append(table)

    elements.append(Spacer(1, 20))

    footer = Paragraph(
        "<font size=10 color='grey'>Generated by PipelineGuard v2.0</font>",
        styles["Normal"]
    )

    elements.append(footer)

    doc.build(elements)

    return pdf_path